### ISSUE TITLE
Screenshots duplicated/transformed wrong.

### ISSUE THREAD

**Issue by dnfm** [emersion/grim#73]
I've found yet another (probably edge case) issue with screenshots on my new set up.

My set up is admittedly very strange.

I have:
1 4k display at the top
4 1080p displays beneath it in 2x2 (This is actually a 4k dispay that supports pbp as 4 separate inputs.)
1 1080p display on the right of those in portrait (headless doing vnc to a wayvnc session)
1 1080p display beneath that in regular orientation (headless doing vnc to a wayvnc session)

And screenshots are completely messed up.

The screenshot shows the 4k as a 1080p transformed 90 degrees and it actually screenshots the headless output (just sideways)
The 2x2 displays are all mirrors of the same headless output as the 4k, and all transformed incorrectly to boot.
Also, the 5 screens that are all mirrors of each other are showing artifacts on the side of windows that are not currently visible.

The only display that is correct is the headless-2 display in the bottom right.

I've attached the screenshot, my swaymsg -t get_outputs, and a photo taken with my cell phone of what they actually look like (you can ignore the laptop on the left; it's not part of this configuration/setup.)

(Yes, I know, that's a lot of screens.)
![screenshot-scaled](https://user-images.githubusercontent.com/5280109/81003382-cee9a780-8e18-11ea-84fa-aa2a2c45e983.png)

![pic](https://user-images.githubusercontent.com/5280109/81003496-f9d3fb80-8e18-11ea-80c5-2ad4956de2c9.jpg)

```
Output DP-1 'Goldstar Company Ltd LG Ultra HD 0x00005750'
  Current mode: 1920x1080 @ 60.000000 Hz
  Position: 1920,2160
  Scale factor: 1.000000
  Scale filter: nearest
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 2
  Max render time: off
  Adaptive sync: disabled
  Available modes:
    640x480 @ 59.939999 Hz
    640x480 @ 59.939999 Hz
    640x480 @ 60.000000 Hz
    720x480 @ 59.939999 Hz
    720x480 @ 60.000000 Hz
    800x600 @ 60.317001 Hz
    1024x768 @ 60.004002 Hz
    1280x720 @ 59.939999 Hz
    1280x720 @ 60.000000 Hz
    1280x720 @ 60.000000 Hz
    1280x800 @ 59.910000 Hz
    1440x900 @ 60.000000 Hz
    1280x1024 @ 60.020000 Hz
    1600x900 @ 60.000000 Hz
    1680x1050 @ 60.000000 Hz
    1920x1080 @ 59.939999 Hz
    1920x1080 @ 60.000000 Hz
    1920x1080 @ 60.000000 Hz

Output DP-2 'Goldstar Company Ltd LG Ultra HD 0x00005750'
  Current mode: 1920x1080 @ 60.000000 Hz
  Position: 0,3240
  Scale factor: 1.000000
  Scale filter: nearest
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 3
  Max render time: off
  Adaptive sync: disabled
  Available modes:
    640x480 @ 59.939999 Hz
    640x480 @ 59.939999 Hz
    640x480 @ 60.000000 Hz
    720x480 @ 59.939999 Hz
    720x480 @ 60.000000 Hz
    800x600 @ 60.317001 Hz
    1024x768 @ 60.004002 Hz
    1280x720 @ 59.939999 Hz
    1280x720 @ 60.000000 Hz
    1280x720 @ 60.000000 Hz
    1280x800 @ 59.910000 Hz
    1440x900 @ 60.000000 Hz
    1280x1024 @ 60.020000 Hz
    1600x900 @ 60.000000 Hz
    1680x1050 @ 60.000000 Hz
    1920x1080 @ 59.939999 Hz
    1920x1080 @ 60.000000 Hz
    1920x1080 @ 60.000000 Hz

Output HDMI-A-1 'Goldstar Company Ltd LG Ultra HD 0x00005750' (focused)
  Current mode: 1920x1080 @ 60.000000 Hz
  Position: 1920,3240
  Scale factor: 1.000000
  Scale filter: nearest
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 4
  Max render time: off
  Adaptive sync: disabled
  Available modes:
    640x480 @ 59.939999 Hz
    640x480 @ 59.939999 Hz
    640x480 @ 60.000000 Hz
    720x480 @ 59.939999 Hz
    720x480 @ 60.000000 Hz
    800x600 @ 60.317001 Hz
    1024x768 @ 60.004002 Hz
    1280x720 @ 59.939999 Hz
    1280x720 @ 60.000000 Hz
    1280x720 @ 60.000000 Hz
    1280x800 @ 59.910000 Hz
    1440x900 @ 60.000000 Hz
    1280x1024 @ 60.020000 Hz
    1600x900 @ 60.000000 Hz
    1680x1050 @ 60.000000 Hz
    1920x1080 @ 59.939999 Hz
    1920x1080 @ 60.000000 Hz
    1920x1080 @ 60.000000 Hz

Output DVI-D-1 'Goldstar Company Ltd LG Ultra HD 0x00005750'
  Current mode: 1920x1080 @ 60.000000 Hz
  Position: 0,2160
  Scale factor: 1.000000
  Scale filter: nearest
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 1
  Max render time: off
  Adaptive sync: disabled
  Available modes:
    640x480 @ 59.939999 Hz
    640x480 @ 59.939999 Hz
    640x480 @ 60.000000 Hz
    720x480 @ 59.939999 Hz
    720x480 @ 60.000000 Hz
    800x600 @ 60.317001 Hz
    1024x768 @ 60.004002 Hz
    1280x720 @ 59.939999 Hz
    1280x720 @ 60.000000 Hz
    1280x720 @ 60.000000 Hz
    1280x800 @ 59.910000 Hz
    1440x900 @ 60.000000 Hz
    1280x1024 @ 60.020000 Hz
    1600x900 @ 60.000000 Hz
    1680x1050 @ 60.000000 Hz
    1920x1080 @ 59.939999 Hz
    1920x1080 @ 60.000000 Hz
    1920x1080 @ 60.000000 Hz

Output HEADLESS-1 'headless headless '
  Current mode: 1920x1080 @ 60.000000 Hz
  Position: 3840,1000
  Scale factor: 1.000000
  Scale filter: nearest
  Subpixel hinting: unknown
  Transform: 270
  Workspace: 5
  Max render time: off
  Adaptive sync: disabled

Output HEADLESS-2 'headless headless '
  Current mode: 1920x1080 @ 60.000000 Hz
  Position: 3840,2920
  Scale factor: 1.000000
  Scale filter: nearest
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 6
  Max render time: off
  Adaptive sync: disabled

Output HDMI-A-2 'ViewSonic Corporation VX4380 SERIES 0x00000101'
  Current mode: 3840x2160 @ 60.000000 Hz
  Position: 0,0
  Scale factor: 1.000000
  Scale filter: nearest
  Subpixel hinting: unknown
  Transform: normal
  Workspace: 7
  Max render time: off
  Adaptive sync: disabled
  Available modes:
    720x400 @ 70.082001 Hz
    640x480 @ 59.939999 Hz
    640x480 @ 59.939999 Hz
    640x480 @ 60.000000 Hz
    640x480 @ 66.667000 Hz
    640x480 @ 72.808998 Hz
    640x480 @ 75.000000 Hz
    720x480 @ 59.939999 Hz
    720x480 @ 60.000000 Hz
    720x576 @ 50.000000 Hz
    800x600 @ 56.250000 Hz
    800x600 @ 60.317001 Hz
    800x600 @ 72.188004 Hz
    800x600 @ 75.000000 Hz
    832x624 @ 74.551003 Hz
    1440x480 @ 59.939999 Hz
    1440x480 @ 59.939999 Hz
    1440x480 @ 60.000000 Hz
    1440x480 @ 60.000000 Hz
    1024x768 @ 60.004002 Hz
    1024x768 @ 70.069000 Hz
    1024x768 @ 75.028999 Hz
    1280x720 @ 50.000000 Hz
    1280x720 @ 59.939999 Hz
    1280x720 @ 60.000000 Hz
    1152x864 @ 75.000000 Hz
    1280x800 @ 59.997002 Hz
    1440x900 @ 59.901001 Hz
    1280x1024 @ 60.020000 Hz
    1280x1024 @ 75.025002 Hz
    1600x900 @ 60.000000 Hz
    1400x1050 @ 59.948002 Hz
    1680x1050 @ 59.882999 Hz
    1600x1200 @ 60.000000 Hz
    1920x1080 @ 50.000000 Hz
    1920x1080 @ 59.939999 Hz
    1920x1080 @ 60.000000 Hz
    1920x1080 @ 60.000000 Hz
    1920x1200 @ 59.997002 Hz
    2560x1440 @ 59.951000 Hz
    3840x1080 @ 59.967999 Hz
    1920x2160 @ 59.999001 Hz
    3840x2160 @ 23.976000 Hz
    3840x2160 @ 24.000000 Hz
    3840x2160 @ 29.981001 Hz
    3840x2160 @ 50.000000 Hz
    3840x2160 @ 59.939999 Hz
    3840x2160 @ 60.000000 Hz
    4096x2160 @ 50.000000 Hz
    4096x2160 @ 59.939999 Hz
    4096x2160 @ 60.000000 Hz
    3840x2160 @ 59.997002 Hz

```

**Comment by hedgepigdaniel** [comment]
Mine also doesn't work, presumeably a change in wlroots/sway broke it?

My setup hasn't changed since https://github.com/emersion/grim/commit/8f9d60885ce2f9bd66cd93d3378dcb6866d4588a which fixed it for me, except that I've upgraded wlroots and sway to the latest versions.

```
Output eDP-1 'Sharp Corporation 0x148D 0x00000000' (focused)
  Current mode: 3840x2160 @ 59.997002 Hz
  Position: 2880,600
  Scale factor: 2.000000
  Transform: normal

Output DP-4 'Dell Inc. DELL U2515H X48H66C10TWL'
  Current mode: 2560x1440 @ 59.951000 Hz
  Position: 1440,0
  Scale factor: 1.000000
  Transform: 270
```

For me the problem is that on DP-4, the screenshots are rotated by 180 degrees, i.e. upside down.

**Comment by emersion** [comment]
This should be fixed by https://github.com/emersion/grim/commit/8f9d60885ce2f9bd66cd93d3378dcb6866d4588a

**Comment by dnfm** [comment]
I too am already running a version containing that commit.

**Comment by hedgepigdaniel** [comment]
OK, I realised my mistake: I was running the latest version of grim from git, but the stable release of sway. That combination doesn't work - you need either both stable, or both git, since the rotation direction was reversed in both.

So I think this issue can be closed.

**Comment by dnfm** [comment]
Nope.

I've always run the latest grim from git and the latest wayland/wlroots.

And for posterity, I just did a git pull on my repos, rebuilt, and tried again: still an issue.

**Comment by dnfm** [comment]
A commit somewhere along the line between when I reported this and now (though not 8f9d608) seems to have fixed it.
